---
- name: Resource management with network.base
  hosts: "*1"
  gather_facts: false

  tasks:
    - name: Capability detection
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        action: list
